name: test

on: workflow_dispatch

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
          $x = @{
            job= @(
              @{
                var1="a"
                var2="b"
              },
              @{
                var1="c"
                var2="d"
              }
            )
          }

          $x.job += @{ 
            var1="e" 
            var2="f" 
          }

          write-output "matrix=$(convertto-Json $x -Compress)" >> $env:GITHUB_OUTPUT
      shell: pwsh
  scatter:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.init.outputs.matrix)}}
    steps:
    - name: "Print matrix"
      run: |
          echo $env:JSON
          echo $env:VAR
      env:
        VAR: ${{ matrix.job }}
        JSON: ${{ toJson(matrix) }}
      shell: pwsh
  merge:
    needs: scatter
    runs-on: ubuntu-latest
    steps:
    - run: echo "DONE!"
