name: test

on: workflow_dispatch

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
         write-output "matrix={jobs: [1,2,3]}" >> $env:GITHUB_OUTPUT
      shell: pwsh
  scatter:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        job: ${{fromJson(needs.init.outputs.matrix)}}
    steps:
    - name: "Print matrix"
      run: |
         echo "$VAR"
      env:
        VAR: "${{ matrix.job }}"
      shell: pwsh
  merge:
    needs: scatter
    runs-on: ubuntu-latest
    steps:
    - run: echo "DONE!"
